### ISSUE TITLE
Negative width when components only contain spaces

### ISSUE THREAD

**Issue by Draycia** [KingOfSquares/pixel-width#7]
It seems when components only contain spaces, their width is the amount of spaces but negative.
Which results in the `CenterAPI.center` never exiting its if loop.

`CenterAPI.center(Component.text(" "));`
https://paste.gg/p/anonymous/ae2ec3c831574270a5aeb7601399cf87

Edit:
Using 1.1.0-SNAPSHOT from OSSRH

**Comment by Draycia** [comment]
It seems using `CenterAPI.center(Component.text("1111"), Component.text(" "));` also triggers the issue, however replacing the second argument with `Component.text("1")` does not result in any issues, and the component is seemingly centered fine.

**Comment by KingOfSquares** [comment]
Solved In #8
